FROM node:20-alpine

WORKDIR /app

# Copy prisma schema first for generate step
COPY package*.json ./
COPY prisma ./prisma
RUN npm install
RUN npx prisma generate

COPY . .

EXPOSE 5000
CMD ["node", "src/index.js"]