const router = require("express").Router();
const authRoutes = require("./auth.routes");
const patientRoutes = require("./patient.routes");
const doctorRoutes = require("./doctor.routes");
const healthWorkerRoutes = require("./healthWorker.routes");
const facilityRoutes = require("./facility.routes");
const appointmentRoutes = require("./appointment.routes");
const queueRoutes = require("./queue.routes");
const recordRoutes = require("./record.routes");
const referralRoutes = require("./referral.routes");
const diagnosticRoutes = require("./diagnostic.routes");
const medicineRoutes = require("./medicine.routes");
const followUpRoutes = require("./followUp.routes");
const notificationRoutes = require("./notification.routes");
const emergencyRoutes = require("./emergency.routes");
const analyticsRoutes = require("./analytics.routes");
const aiRoutes = require("./ai.routes");
const dashboardRoutes = require("./dashboard.routes");

router.get("/", (req, res) => res.json({ service: "Nirovveda API", version: "1.0.0" }));
router.use("/auth", authRoutes);
router.use("/patients", patientRoutes);
router.use("/doctors", doctorRoutes);
router.use("/health-workers", healthWorkerRoutes);
router.use("/facilities", facilityRoutes);
router.use("/appointments", appointmentRoutes);
router.use("/queue", queueRoutes);
router.use("/records", recordRoutes);
router.use("/referrals", referralRoutes);
router.use("/diagnostics", diagnosticRoutes);
router.use("/medicines", medicineRoutes);
router.use("/follow-ups", followUpRoutes);
router.use("/notifications", notificationRoutes);
router.use("/emergency", emergencyRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/ai", aiRoutes);
router.use("/dashboard", dashboardRoutes);

module.exports = router;